import Head from "next/head"
import styles from "../styles/Home.module.css"
import Profile from "./profile"
import Nav from "../components/Nav"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>EY Web3 Discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Profile />
    </div>
  )
}
